/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Restaurant.RestaurantManager;

import ui.Grocery.GroceryManager.*;
import business.EcoSystem.EcoSystem;
import business.Enterprise.GroceryEnterprise;
import business.Enterprise.RestaurantEnterprise;
import business.Item.FoodItem;
import business.Item.GroceryItem;
import business.Network.Network;
import business.UserAccount.UserAccount;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAI SRIDHAR
 */
public class ManageItemsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageItemsJPanel
     */
     JPanel workArea;
    UserAccount account;
    EcoSystem ecosystem;
    RestaurantEnterprise res;
    Network network;
    public ManageItemsJPanel(JPanel workArea, UserAccount account, EcoSystem ecosystem, RestaurantEnterprise enterprise) {
        initComponents();this.workArea = workArea;
        this.account = account;
        this.ecosystem = ecosystem;
        this.res = enterprise;
        network = ecosystem.getNetworkList().get(0);
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 62, 70));

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItems);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(95, 95, 95)
                        .addComponent(jButton1)
                        .addGap(87, 87, 87)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(btnDelete))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblItems.getSelectedRow();

        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an item to delete!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        FoodItem selectedItem = (FoodItem) tblItems.getValueAt(selectedRow, 0);

        int result = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete " + selectedItem.getName() + "?", 
            "Confirm Deletion", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.WARNING_MESSAGE);

        if (result == javax.swing.JOptionPane.YES_OPTION) {
            res.getMenu().getMenu().remove(selectedItem);

            javax.swing.JOptionPane.showMessageDialog(this, "Item deleted successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            populateTable(); 
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      int selectedRow = tblItems.getSelectedRow();

        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an item to edit.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        FoodItem selectedItem = (FoodItem) tblItems.getValueAt(selectedRow, 0);

        EditItemJPanel editPanel = new EditItemJPanel(workArea, account, ecosystem, res);
        editPanel.setSize(600,600);
        editPanel.setItemName(selectedItem.getName());
        editPanel.setItemPrice(String.valueOf(selectedItem.getPrice()));
        

        int result = javax.swing.JOptionPane.showConfirmDialog(this, editPanel, "Edit Item", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);

        if (result == javax.swing.JOptionPane.OK_OPTION) {
            String itemName = editPanel.getItemName();
            String itemPriceText = editPanel.getItemPrice();

            if (itemName.isEmpty() || itemPriceText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "All fields are required!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                double itemPrice = Double.parseDouble(itemPriceText);

                selectedItem.setName(itemName);
                selectedItem.setPrice(itemPrice);

                javax.swing.JOptionPane.showMessageDialog(this, "Item updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                populateTable();

            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid price or availability. Please enter numeric values.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame addItemFrame = new JFrame("Add Grocery Item");
        addItemFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addItemFrame.setSize(600, 600);
        addItemFrame.setLocationRelativeTo(null);

        AddItemJPanel addItemPanel = new AddItemJPanel(workArea, account, ecosystem, res);
        addItemFrame.add(addItemPanel);

        addItemFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblItems.getModel();
    model.setRowCount(0);

    for (FoodItem item : res.getMenu().getMenu()) {
        Object[] row = new Object[2];
        row[0] = item;
        row[1] = item.getPrice();
        model.addRow(row);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItems;
    // End of variables declaration//GEN-END:variables
}
