/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Restaurant.RestaurantEmployees;

import business.EcoSystem.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.RestaurantEnterprise;
import business.Organization.Organization;
import business.UserAccount.EmployeeAccount;
import business.UserAccount.UserAccount;
import business.WorkQueue.OrderRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.LoginJPanel;

/**
 *
 * @author SAI SRIDHAR
 */
public class RestaurantEmployeeWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form RestaurantEmployeeWorkArea
     */
    EmployeeAccount ea;
    Organization organization;
    EcoSystem ecosystem;
    JPanel workarea;
    RestaurantEnterprise enterprise;
    public RestaurantEmployeeWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.ea = (EmployeeAccount)account;
        this.workarea = userProcessContainer;
        this.organization = organization;
        this.ecosystem = business;
        this.enterprise = (RestaurantEnterprise) enterprise;
        populateTable();
    }
    
    private void populateTable() {
    DefaultTableModel dtm = (DefaultTableModel) workRequestJTable.getModel();
    dtm.setRowCount(0);
    System.out.println("WorkRequest List size: " + ea.getWorkQueue().getWorkRequestList().size());
    for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
        if(wr.getStatus().equals("Assigned to Employee") || wr.getStatus().equals("In Progress")){
            OrderRequest or = (OrderRequest) wr;
            Object row[] = new Object[2];
            row[0] = or;
         
            row[1] = or.getStatus();
            dtm.addRow(row);
        }
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        btnFinishOrder = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 62, 70));

        workRequestJTable.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Order Id", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        assignJButton.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        btnFinishOrder.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        btnFinishOrder.setText("Finish Order");
        btnFinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishOrderActionPerformed(evt);
            }
        });

        refreshJButton.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(refreshJButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFinishOrder))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnLogout)
                .addGap(26, 26, 26)
                .addComponent(refreshJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignJButton)
                    .addComponent(btnFinishOrder))
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        
        int selectedRow = workRequestJTable.getSelectedRow();
    if (selectedRow < 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please select an order to assign to yourself");
        return;
    }
    OrderRequest selectedOrder = (OrderRequest) workRequestJTable.getValueAt(selectedRow, 0);

    if (!selectedOrder.getStatus().equalsIgnoreCase("Assigned to Employee")) {
        javax.swing.JOptionPane.showMessageDialog(null, "Order is not ready to be assigned");
        return;
    }

    selectedOrder.setStatus("In Progress");
    selectedOrder.setAssignedTo(ea); // Assuming setAssignedTo(UserAccount) is available
    javax.swing.JOptionPane.showMessageDialog(null, "Order assigned to you successfully");
    populateTable();

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void btnFinishOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishOrderActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
    if (selectedRow < 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please select an order to finish");
        return;
    }
    OrderRequest selectedOrder = (OrderRequest) workRequestJTable.getValueAt(selectedRow, 0);

    if (!selectedOrder.getStatus().equalsIgnoreCase("In Progress")) {
        javax.swing.JOptionPane.showMessageDialog(null, "Only in-progress orders can be marked as finished");
        return;
    }

    selectedOrder.setStatus("Order Prepared");
    javax.swing.JOptionPane.showMessageDialog(null, "Order marked as completed");
    populateTable(); // Refresh the table
    }//GEN-LAST:event_btnFinishOrderActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        workarea.removeAll();

    LoginJPanel loginPanel = new LoginJPanel(workarea);
    workarea.add("LoginJPanel", loginPanel);

    CardLayout layout = (CardLayout) workarea.getLayout();
    layout.next(workarea);

    javax.swing.JOptionPane.showMessageDialog(null, "Logged out successfully.");
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnFinishOrder;
    private javax.swing.JButton btnLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
